### ISSUE TITLE
Magdalena Jankowska-Grygier, Weronika Szoffer, Paweł Folta

### ISSUE THREAD

**Issue by weronika192** [BERENZ/Dydaktyka#61]
![1](https://cloud.githubusercontent.com/assets/11577382/8035126/294b94a0-0dee-11e5-993d-cdf1ca3075f6.jpeg)
![2](https://cloud.githubusercontent.com/assets/11577382/8035131/2d0aeb0e-0dee-11e5-8c6d-23f58abf3f9c.jpeg)
![3](https://cloud.githubusercontent.com/assets/11577382/8035134/2f472752-0dee-11e5-9176-79e13d768809.JPG)
![4](https://cloud.githubusercontent.com/assets/11577382/8035137/318523e8-0dee-11e5-9676-517a652678a3.jpeg)
![5](https://cloud.githubusercontent.com/assets/11577382/8035138/34459658-0dee-11e5-9392-659a562378bd.jpeg)

KODY:
1. 
library(dplyr)
library(ggplot2)
library(scales)

load('/Users/TeTaim/Desktop/matury_kraj.RData')
matury <- tbl_df(matury)

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

matury <- matury %>%
  mutate(wyniki_proc = wyniki_matur / 50)

matury$typ <- factor(matury$typ,
                     levels = c('LO', 'LOU', 'LP', 'T', 'TU'),
                     labels = c('Liceum Ogólnokszt.',
                                'Lic. Og. Uzup.',
                                'Liceum Profilowane',
                                'Technikum',
                                'Technikum Uzup.'))

ggplot(matury, 
       aes(x = matura_nazwa, 
           y = wyniki_proc,
           fill = typ)) + 
  stat_summary(fun.y = 'median', 
               geom = 'bar', 
               colour = 'black',
               position = position_dodge(),  
               aes(width = 0.8)) +
  scale_y_continuous(labels = percent) +
  labs(x = 'Przedmioty', 
       y = 'Mediana wyniku matury', 
       title = 'Mediana wyników matur z poszczególnych przedmiotów \n w podziale na typy szkół w latach 2010-2014') + 
  theme_bw() +
  theme(plot.title = element_text(size = 15, colour="red"), 
        axis.text.x = element_text(size = 10, angle=20),
        axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15),
        legend.title = element_blank(),
        strip.text.x = element_text(size = 13)
  ) +
  scale_fill_manual(values=cbPalette)

2. 
#Ustawienie working Directory. 
#Należy podać lokalizację repozytorium Dydaktyka/WIRDS
setwd("C:/Users/TeTaim/Desktop")

#wczytujemy workspace z danymi z matur
load("matury_kraj.RData")

#Wykres
matury %>%
  select(matura_nazwa, matura_miedzynarodowa, wyniki_matur) %>%
  filter(matura_miedzynarodowa!='NA') %>%
  mutate(matura_miedzynarodowa= ifelse(matura_miedzynarodowa=='TRUE','Matura międzynarodowa','Matura krajowa'))%>%
  group_by(matura_nazwa, matura_miedzynarodowa) %>%
  summarize(srednia=mean(wyniki_matur, na.rm=T)/60*100,
            liczebnosc = n()) %>%
  ggplot(data=.,
         aes(x=matura_nazwa,
             y=srednia,
             fill=matura_miedzynarodowa,
             ymax = 100))+
  geom_bar(stat='identity',
           position='dodge',
           colour='black')+ 
  theme_bw() +
  theme(plot.title = element_text(size = 15, colour="red"), 
        axis.text.x = element_text(size = 10, angle=20),
        axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15),
        legend.title = element_blank(),
        strip.text.x = element_text(size = 13)
  ) +
  ylab('Średni wynik (%)')+
  xlab('Przedmiot')+
  scale_fill_discrete(name='Uczniowie:')+
  ggtitle('Średni wynik matur z poszczególnych przedmiotów \n uczniów piszących maturę międzynarodową i krajową')+
  scale_y_continuous(limits=c(0,100))+
  geom_text(aes(label = round(srednia, digits=1)), 
            position = position_dodge(width=0.80), vjust=-0.4, size=4.0) +
  geom_hline(aes(yintercept = 30))

3. 
setwd("C:/Users/TeTaim/Desktop")
load('matury.RData')
library(sjPlot)
library(dplyr)
library(ggplot2)
library(scales)

matury <- matury %>%
  select (wyniki_matur, rok, rodzaj_gminy)%>%
  filter(rok==2010)

matury$klasa <- factor(matury$rodzaj_gminy,
                       levels = c('wiejska', 'miejsko-wiejska', 'miejska', 'dzielnica m.st. Warszawy'),
                       labels = c('1',
                                  '2',
                                  '3', '4'))

matury$klasa <- set_val_labels(matury$klasa,
                               lab=c("wiejska", "miejsko-wiejska", "miejska", "dzielnica m.st. Warszawy"))
matury$klasa <- set_var_labels(matury$klasa,
                               lab='Rodzaj gminy')

sjt.frq(matury$klasa, 
        variableLabels='Rodzaj gminy a ilość maturzystów w roku 2010',    ##tytuł tabeli
        encoding='cp1250',         ##zmiana kodowania
        stringValue="Rodzaj gminy",
        stringPerc='%',
        stringValidPerc='% ważnych',
        stringCumPerc='skumulowany %',
        showSummary=TRUE,
        stringMissingValue='Braki danych')

4.
#Wykres 4
setwd("C:/Users/TeTaim/Desktop")
load("matury_kraj.RData")

library(dplyr)
library(ggplot2)
library(ggthemes)

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

czwarty <- matury %>%
  select(wyniki_matur, matura_nazwa, rok)%>%
  filter (matura_nazwa==c('geografia podstawowa','matematyka podstawowa','informatyka podstawowa'))%>%
  group_by(matura_nazwa, rok)%>%
  summarise(procent=mean(wyniki_matur*2))

czwarty$typ <- factor(czwarty$matura_nazwa,
                     levels = c('geografia podstawowa','matematyka podstawowa','informatyka podstawowa'),
                     labels = c('geografia podstawowa',
                                'matematyka podstawowa',
                                'informatyka podstawowa'))
ggplot(data=czwarty,
       aes(x=rok,
           y=procent,
           colour=typ,
           group=typ,
           label=procent))+
  geom_point(size=3)+
  geom_line(size=1)+
  theme_bw()+
  scale_colour_tableau(name='Typ szkoły')+
  geom_line(aes(x=rok,y=30), colour='black', linetype = 3, size=0.8)+
  xlab('Rok')+
  ylab('Procentowe wyniki matur')+
  ggtitle('Średnie wyniki matur podstawowych \n na przestrzeni lat 2010-2014')+
  theme(plot.title=(element_text(size = 15)))+
  geom_hline(aes(yintercept = 30))+
  scale_fill_manual(values=cbPalette)+
  scale_y_continuous(limits=c(0,100))

5.
setwd("C:/Users/TeTaim/Desktop")
load('matury_kraj.RData')
library(sjPlot)
library(dplyr)
library(ggplot2)
library(scales)

matury <- matury %>%
  select (matura_nazwa, wyniki_matur, rok, rodzaj_gminy)%>%
  filter(rok==2010)%>%
  filter(matura_nazwa!='geografia rozszerzona')
  
  matury$klasa <- factor(matury$rodzaj_gminy,
                         levels = c('wiejska', 'miejsko-wiejska', 'miejska', 'dzielnica m.st. Warszawy'),
                         labels = c('wiejska',
                                    'miejsko-wiejska',
                                    'miejska',
                                    'dzielnica m.st. Warszawy'))

ggplot(data=matury, aes(x=klasa, y=wyniki_matur*2)) +  
  geom_boxplot() +
  theme_bw()+
  xlab('Rodzaj gminy')+
  ylab('Procentowe wyniki matur')+
  ggtitle('Porównanie wyników matur pod względem rodzaju gminy')+
  theme(plot.title=(element_text(size = 15, colour="red")))

**Comment by BERENZ** [comment]
Dziękuję
